/**
 * Per-scenario state for the CGS e2e suite. No browser (CGS is an XRPC HTTP
 * API): the World holds the last HTTP response, the resolved DIDs, and a little
 * bookkeeping. Per-role passwords are read from testEnv at mint time rather than
 * stored here.
 */
import { World, setWorldConstructor } from '@cucumber/cucumber'
import { testEnv } from './env.js'
import type { HttpSink } from './cgs.js'

export class CgsWorld extends World implements HttpSink {
  // --- last HTTP response (the failure hook reads lastHttpBody) ---
  lastHttpStatus?: number
  lastHttpJson?: Record<string, unknown>
  lastHttpBody?: string
  lastHttpHeaders?: Headers

  // --- resolved identity state (deterministic; re-derived in each Background) ---
  serviceDid: string = testEnv.serviceDid
  groupDid?: string
  groupHandle?: string
  ownerDid?: string
  adminDid?: string
  memberDid?: string
  outsiderDid?: string

  // --- bookkeeping across steps within a scenario ---
  createdRecordUri?: string
  uploadedBlob?: Record<string, unknown>
  /** Unique handle generated by the @manual register feature, carried between
   *  its register-then-conflict scenarios. */
  registerHandle?: string

  get env() {
    return testEnv
  }

  /** Mark a step pending (cleanly skips the rest of the scenario) when a needed
   *  optional secret is absent — mirrors ePDS skipIfNoMailpit(). */
  skipIfNo(value: string | undefined): 'pending' | undefined {
    return value ? undefined : 'pending'
  }
}

setWorldConstructor(CgsWorld)
